version: 40
jobs:
- name: Push to GitHub
  steps:
  - !PushRepository
    name: GitHub Sync
    remoteUrl: https://github.com/VnUgE/vnbuild.git
    userName: VnUgE
    passwordSecret: git-access-token
    force: false
    condition: SUCCESSFUL
    optional: false
  - !PushRepository
    name: Codeberg push sync
    remoteUrl: https://codeberg.org/VnUgE/vnbuild.git
    userName: VnUgE
    passwordSecret: codeberg-access-token
    force: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - !TagCreateTrigger {}
  - !BranchUpdateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: Mock Build
  jobExecutor: windows
  steps:
  - !CommandStep
    name: Checkout Code
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        git clone @server_url@/@project_path@ --branch @branch@
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - !CommandStep
    name: VNBuild build
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        vnbuild build --verbose --no-delay
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - !CommandStep
    name: VNBuild publish
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        vnbuild publish --verbose
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - !BranchUpdateTrigger
    branches: -master
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: Build and publish
  jobExecutor: publish-agents
  steps:
  - !CommandStep
    name: Checkout Code
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        git clone @server_url@/@project_path@ --branch @branch@
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - !CommandStep
    name: VNBuild build
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        vnbuild build --no-delay
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - !CommandStep
    name: VNBuild publish
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        vnbuild publish --ftp "@secret:ftp_server_address@" --sign
    envVars:
    - name: FTP_USERNAME
      value: '@secret:ftp_username@'
    - name: FTP_PASSWORD
      value: '@secret:ftp_password@'
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - !BranchUpdateTrigger
    branches: master
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
