version: 35
jobs:
- name: Push to GitHub
  steps:
  - !PushRepository
    name: GitHub Sync
    remoteUrl: https://github.com/VnUgE/vnbuild.git
    userName: VnUgE
    passwordSecret: git-access-token
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !TagCreateTrigger
    projects: vnbuild
  - !BranchUpdateTrigger
    projects: vnbuild
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: Pull from GitHub
  steps:
  - !PullRepository
    name: Sync from GitHub
    remoteUrl: https://github.com/VnUgE/vnbuild.git
    userName: VnUgE
    passwordSecret: git-access-token
    refs: refs/heads/* refs/tags/*
    withLfs: false
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !ScheduleTrigger
    cronExpression: 0 15 10 ? * *
    projects: vnbuild
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600

- name: Build and publish
  jobExecutor: primary-shell-executor
  steps:
  - !CheckoutStep
    name: Code checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    checkoutPath: '@project_name@/'
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: VNBuild build
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        vnbuild build -S --verbose
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: VNBuild publish
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        vnbuild publish --ftp "@secret:ftp_server_address@" --sign --verbose
    envVars:
    - name: FTP_USERNAME
      value: '@secret:ftp_username@'
    - name: FTP_PASSWORD
      value: '@secret:ftp_password@'
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
