version: 43
jobs:
- name: Push to GitHub
  steps:
  - type: PushRepository
    name: GitHub Sync
    remoteUrl: https://github.com/VnUgE/vnbuild.git
    userName: VnUgE
    passwordSecret: git-access-token
    force: false
    condition: SUCCESSFUL
    optional: false
  - type: PushRepository
    name: Codeberg push sync
    remoteUrl: https://codeberg.org/VnUgE/vnbuild.git
    userName: VnUgE
    passwordSecret: codeberg-access-token
    force: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - type: TagCreateTrigger
  - type: BranchUpdateTrigger
    userMatch: anyone
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600

- name: Mock Build
  jobExecutor: windows
  steps:
  - type: CommandStep
    name: Checkout Code
    runInContainer: false
    interpreter:
      type: DefaultInterpreter
      commands: |
        git clone @server_url@/@project_path@ --branch @branch@
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: VNBuild build
    runInContainer: false
    interpreter:
      type: DefaultInterpreter
      commands: |
        vnbuild build --verbose --no-delay
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: VNBuild publish
    runInContainer: false
    interpreter:
      type: DefaultInterpreter
      commands: |
        vnbuild publish --verbose
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - type: PublishArtifactStep
    name: publish bins
    sourcePath: '@project_name@/src/bin'
    artifacts: '*'
    condition: SUCCESSFUL
    optional: true
  triggers:
  - type: BranchUpdateTrigger
    branches: -master
    userMatch: anyone
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600

- name: Build and publish
  jobExecutor: publish-agents
  steps:
  - type: CommandStep
    name: Checkout Code
    runInContainer: false
    interpreter:
      type: DefaultInterpreter
      commands: |
        git clone @server_url@/@project_path@ --branch @branch@
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: VNBuild build
    runInContainer: false
    interpreter:
      type: DefaultInterpreter
      commands: |
        vnbuild build --no-delay
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: VNBuild publish
    runInContainer: false
    interpreter:
      type: DefaultInterpreter
      commands: |
        vnbuild publish --ftp "@secret:ftp_server_address@" --sign
    envVars:
    - name: FTP_USERNAME
      value: '@secret:ftp_username@'
    - name: FTP_PASSWORD
      value: '@secret:ftp_password@'
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - type: BranchUpdateTrigger
    branches: master
    userMatch: anyone
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
