version: 37
jobs:
- name: Push to GitHub
  steps:
  - !PushRepository
    name: GitHub Sync
    remoteUrl: https://github.com/VnUgE/vnbuild.git
    userName: VnUgE
    passwordSecret: git-access-token
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !TagCreateTrigger
    projects: vnbuild
  - !BranchUpdateTrigger
    projects: vnbuild
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: Mock Build
  jobExecutor: windows
  steps:
  - !CommandStep
    name: Checkout Code
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        git clone @server_url@/@project_name@ --branch @branch@
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: VNBuild build
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        vnbuild build --verbose --no-delay
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: mock publish
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        vnbuild publish --verbose
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishArtifactStep
    name: publish image artifacts
    sourcePath: '@project_name@/containers/bin'
    artifacts: '*'
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: -master
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
- name: Publish master
  jobExecutor: publish-agents
  steps:
  - !CommandStep
    name: Checkout Code
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        git clone @server_url@/@project_name@ --branch @branch@
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: VNBuild build
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        vnbuild build --no-delay
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: VNBuild publish
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        vnbuild publish --ftp "@secret:ftp_server_address@" --sign
    envVars:
    - name: FTP_USERNAME
      value: '@secret:ftp_username@'
    - name: FTP_PASSWORD
      value: '@secret:ftp_password@'
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishArtifactStep
    name: publish server artifacts
    sourcePath: '@project_name@/containers/bin'
    artifacts: '*'
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: master
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
- name: Publish Images
  jobExecutor: docker
  steps:
  - !CommandStep
    name: prep image
    runInContainer: true
    image: ubuntu:25.04
    interpreter: !DefaultInterpreter
      commands: |
        cd @project_name@
        ls -lah
        mkdir fedora ubuntu
        tar -xzf fedora-amd64.tgz -C fedora
        tar -xzf ubuntu-amd64.tgz -C ubuntu
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !BuildImageStep
    name: build fedora image
    buildPath: '@project_name@/fedora'
    output: !RegistryOutput
      tags: vnuge/vnbuild:fedora-latest vnuge/vnbuild:fedora-@commit_hash@
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !BuildImageStep
    name: build ubuntu image
    buildPath: '@project_name@/ubuntu'
    output: !RegistryOutput
      tags: vnuge/vnbuild:ubuntu-latest vnuge/vnbuild:ubuntu-@commit_hash@
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: -master
  jobDependencies:
  - jobName: Mock Build
    requireSuccessful: true
    artifacts: '**'
    destinationPath: '@project_name@'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
