# https://taskfile.dev

version: '3'

vars:
  BINARY_DIR: '{{ .BINDARY_DIR | default "bin" }}'

  LINUX_ARCHES: [ "linux-x64", "linux-arm", "linux-arm64" ]

tasks:

  build:
    desc: "DO NOT USE! Used by vnbuild CI to build the module."
    dir: '{{ .USER_WORKING_DIR }}'
    cmds:
      - for: { var: LINUX_ARCHES }
        cmd: dotnet deb -c release -r {{ .ITEM }} --output {{ .BINARY_DIR }}

      - for: { var: LINUX_ARCHES }
        cmd: dotnet rpm -c release -r {{ .ITEM }} --output {{ .BINARY_DIR }}

  #when build succeeds, archive the output into a tgz
  postbuild_success:
    dir: '{{ .USER_WORKING_DIR }}'
    cmds:
      #pack up source code and put in output
     - task: pack_source

  pack_source:
    internal: true
    dir: '{{ .USER_WORKING_DIR }}'
    vars:
      EXCLUDES:
        --exclude='src/bin/*'
        --exclude='src/obj/*'
      INCLUDES:
        src/*
        LICENSE
        Taskfile.yaml
        README.md
        Module.Taskfile.yaml
        vnbuild.build.sln

    cmds:
      #pack up source code and put in output
     - cmd: cd .. && tar{{ if eq OS "windows" }}.exe{{ end }} 
         {{ .EXCLUDES }} 
         -czf '{{ .USER_WORKING_DIR }}/{{ .BINARY_DIR }}/src.tgz' 
         {{ .INCLUDES }}

  #Remove the output dirs on clean
  clean:
    dir: '{{ .USER_WORKING_DIR }}'
    ignore_error: true
    cmds:
     - for: [ bin/, obj/ ]
       cmd: rm -rf './{{ .ITEM }}'
  