# https://taskfile.dev

version: '3'

includes:
  module: 
    taskfile: './Module.Taskfile.yaml'
    internal: true

tasks:
  #when build succeeds, archive the output into a tgz 
  postbuild_success:
    dir: '{{ .USER_WORKING_DIR }}'
    vars:
      RELEASE_DIR: "./bin/release/{{ .TARGET_FRAMEWORK }}"  
    cmds:
      #pack up source code and put in output
     - task: pack_source

      #remove unnecessary files from the release dir
     - cmd: powershell -Command "
        Get-ChildItem 
        -Recurse 
        -Include *.pdb,*.xml 
        '{{ .RELEASE_DIR }}/' 
        | Remove-Item"

     - task: postbuild_parallel

  postbuild_parallel:
    deps:
     - for: { var: TARGET_ARCHES }
       task: postbuild
       vars: { BUILD_MODE: release, TARGET_OS: '{{ .ITEM }}' }

  postbuild:
    internal: true
    dir: '{{ .USER_WORKING_DIR }}'
    vars:
      BUILD_DIR: "{{ .USER_WORKING_DIR }}/{{ .BINARY_DIR }}/{{ .BUILD_MODE }}/{{ .TARGET_FRAMEWORK }}/{{ .TARGET_OS }}/publish"
      TARGET_DIR: "{{ .USER_WORKING_DIR }}/{{ .BINARY_DIR }}"
    cmds:
     #copy and readme to target
     - cmd: cd .. && powershell cp './build.readme.txt' '{{ .BUILD_DIR }}/readme.txt'
       ignore_error: true

     - cmd: cd "{{ .BUILD_DIR }}" && tar -czf "{{ .TARGET_DIR }}/{{ .TARGET_OS }}-{{ .BUILD_MODE }}.tgz" .

  pack_source:
    internal: true
    dir: '{{ .USER_WORKING_DIR }}'
    vars:
      EXCLUDES:
        --exclude='src/bin/*'
        --exclude='src/obj/*'
        #--exclude='.tarignore'
      INCLUDES:
        src/*
        LICENSE
        Taskfile.yaml
        README.md
        Module.Taskfile.yaml
        vnbuild.build.sln

    cmds:
      #pack up source code and put in output
     - cmd: cd .. && tar {{ .EXCLUDES }} -czf '{{ .USER_WORKING_DIR }}/{{ .BINARY_DIR }}/src.tgz' {{ .INCLUDES }}

  #Remove the output dirs on clean
  clean:
    dir: '{{ .USER_WORKING_DIR }}'
    ignore_error: true
    cmds:
     - for: [ bin/, obj/ ]
       cmd: powershell rm -Recurse './{{ .TARGET }}'
  