
version: '3'

includes:
  module:
    dir: ..
    taskfile: '../Module.Taskfile.yaml'
    internal: true

vars:
  BINARY_DIR: '{{ .BINARY_DIR | default "bin" }}'
  BUILD_DIR: build
  VNBUILD_DIR: '{{ .USER_WORKING_DIR }}/vnbuild'

  BASE_IMAGES: ["ubuntu-amd64", "fedora-amd64"]

tasks:

  build:
    deps:
     - build-vnbuild
    cmds:
     - for: { var: BASE_IMAGES }
       task: build-image
       vars: { BASE_IMAGE_NAME: '{{ .ITEM }}' }

  build-image:
    internal: true
    vars:
      BUILD_DIR: '{{ .BUILD_DIR }}/{{ .BASE_IMAGE_NAME }}'
    cmds:
     - cmd: mkdir -p "{{ .BUILD_DIR }}"
     - cmd: mkdir -p "{{ .BUILD_DIR }}/app"
     - cmd: cp -r "{{ .VNBUILD_DIR }}/" "{{ .BUILD_DIR }}/app"
     - cmd: cp "{{ .BASE_IMAGE_NAME }}.Dockerfile" "{{ .BUILD_DIR }}/Dockerfile"

  postbuild_success:
    vars:
      BINARY_DIR: '{{ .USER_WORKING_DIR }}/{{ .BINARY_DIR }}'
    cmds:
     - cmd: mkdir -p "{{ .BINARY_DIR }}"

     - for: { var: BASE_IMAGES }
       cmd: cd "{{ .BUILD_DIR }}/{{ .ITEM }}" &&
         tar{{ if eq OS "windows" }}.exe{{ end }} -czf "{{ .BINARY_DIR }}/{{ .ITEM }}.tgz" .
     
     - cmd: rm -rf "{{ .VNBUILD_DIR }}" && rm -rf "{{ .BUILD_DIR }}"
       ignore_error: true

  build-vnbuild:
    cmds:
     - task: module:default
       vars:
         CONFIGURATION: 'release'
         CLI_ARGS: '
           -r linux-x64
           --output "{{ .VNBUILD_DIR }}"'

  clean:
    cmds:
     - for: [ vnbuild/, build/, bin/ ]
       cmd: rm -rf "{{ .ITEM }}"
       ignore_error: true