<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AssemblyName>vnbuild</AssemblyName>
    <RootNamespace>VNLib.Tools.Build.Executor</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Vaughn Nugent</Authors>
    <Company>Vaughn Nugent</Company>
    <Description>Automatically builds and produces binaries from git-based modules with proper indexing for web based deployments</Description>
    <Copyright>Copyright © 2025 Vaughn Nugent</Copyright>
    <Product>vnbuild</Product>
    <PackageProjectUrl>https://www.vaughnnugent.com/resources/software/modules/vnbuild</PackageProjectUrl>
    <RepositoryUrl>https://github.com/VnUgE/vnbuild/</RepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <Artifacts>linux-x64-release.tgz,linux-arm-release.tgz,linux-arm64-release.tgz,win-x64-release.tgz,win-arm64-release.tgz,osx-x64-release.tgz,osx-arm64-release.tgz</Artifacts>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentFTP" Version="53.0.1" />
    <PackageReference Include="Typin" Version="3.1.0" />
    <PackageReference Include="LibGit2Sharp" Version="0.31.0" />
    <PackageReference Include="Microsoft.Build" Version="17.11.4" />
    <PackageReference Include="Serilog" Version="4.3.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

</Project>